version: "3.8"

services:
  service: &service
    env_file:
      - ".env"
    build:
      dockerfile: ./docker/service.dockerfile
      context: .
    stop_grace_period: "2s"
    volumes:
      - ./:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  worker:
    <<: *service
    command: ["/bin/sh", "docker/scripts/worker-docker-entrypoint.sh"]

  db:
    image: postgres
    env_file:
      - ".env"
    restart: "unless-stopped"

  redis:
    image: "redis:7.0.0"
    env_file:
      - ".env"
    restart: "unless-stopped"
    stop_grace_period: "2s"
    volumes:
      - "redis:/data"

  devbox:
    <<: *service
    entrypoint: /bin/bash
    stdin_open: true
    tty: true

  pgweb:
    image: sosedoff/pgweb
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
    restart: "unless-stopped"
    ports:
      - "8081:8081"
    links:
      - db
    depends_on:
      - db

volumes:
  redis:
