site_name: Hyacinth
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - Overview: "index.md"
  - "Getting started": "getting-started.md"
  - "Usage guide":
      - "Creating a search": "usage-guide/creating-a-search.md"
      - "Adding filters": "usage-guide/adding-filters.md"
      - "Configuration": "usage-guide/configuration.md"
      - "Plugins":
          - "Craigslist": "usage-guide/plugins/craigslist.md"
          - "Facebook Marketplace": "usage-guide/plugins/marketplace.md"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - admonition
