[tool.pylint.master]
disable="""
C0103,C0114,C0115,C0116,C0200,C0330,C0326,W0703,W0105,R1705,R0901,R0902,R0903,R0904,R0911,R0912,R0913,R0914,
R0915,R0916,R1702,C0206,R0801"""
extension-pkg-whitelist="pydantic"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.black]
line-length = 100

[tool.mypy]
show_column_numbers = true

[[tool.mypy.overrides]]
module = [
    "craigslist",
    "geopy.*",
    "boolean",
    "discord"
]
ignore_missing_imports = true

[tool.poetry]
name = "marketplace-notifier-bot"
version = "0.0.1"
description = "A Discord bot to send notifications for marketplace (Craigslist, Facebook) postings based on complex matching rules."
authors = ["Stephan Lensky <stephanl.public@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/stephanlensky/marketplace-notifier-bot"
repository = "https://github.com/stephanlensky/marketplace-notifier-bot"
include = [
    "LICENSE",
]

# [tool.poetry.scripts]
# amt = "apple_music_tools.main:app"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
"boolean.py" = "^3.8"
"discord.py" = "^1.7.3"
python-craigslist = { git = "git@github.com:stephanlensky/python-craigslist.git" }
geopy = "^2.2.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
isort = "^5.10.1"
mypy = "^0.942"
pylint = "^2.13.3"
docformatter = "^1.4"
types-requests = "^2.27.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"